In [14]:

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from collections import OrderedDict

class NetworkModel(nn.Module):

    def __init__(self, inputDim):

        # Initialize the network layers.

        super(NetworkModel, self).__init__()

        param = torch.randn(inputDim, inputDim)
        param_t = torch.transpose(param,0,1)
        self.weight1 = torch.nn.Parameter(param)
        self.weight1_t = torch.nn.Parameter(param_t)
        #self.relu = torch.nn.ReLU()


    def forward(self, x):

        # A forward function
        # Linear function without activation
        x = F.linear(x, self.weight1)
        #x = self.relu(x)
        x = F.linear(x,self.weight1_t)
        return x





class TrainModel():

    def __init__(self, model, device, learningRate, inputDim, batchSize, numberOfSteps):

        self.device = device
        self.net = model.to(self.device)
        self.optimizer = optim.Adam(self.net.parameters(), lr=learningRate)
        self.inputDim = inputDim
        self.batchSize = batchSize
        self.numberOfSteps = numberOfSteps

    def train(self,):

        for step in range(self.numberOfSteps):

            self.optimizer.zero_grad()
            input = torch.randn((self.batchSize, self.inputDim)).to(self.device)
            output = (1/self.inputDim)*self.net(input)
            loss = F.mse_loss(input, output)
            loss.backward()
            self.optimizer.step()

        parameters = list(self.net.parameters())
        mat1 = parameters[0]
        mat1_rounded = torch.round(mat1)
        mat2 = parameters[1]
        mat2_rounded = torch.round(mat2)
        mat = mat1 @ mat2
        mat_rounded = mat1_rounded @ mat2_rounded
        #print(torch.round(weightFunction), 5)
        #print(weightFunction2)
        print(parameters)
        print("H*Ht = ")
        print(torch.matmul(parameters[0], parameters[1]))
        #print(self.net)
#         print(torch.round(mat1),2)
#         print(torch.round(mat2),3)
#         print(torch.round(mat),4)
#         print(torch.round(mat_rounded),5)

    def test(self,n):

        test_samples = torch.randn(n, self.inputDim).to(self.device)
        preds = self.net(test_samples)
        print("Results: ")
        for i in range(n):
            print(torch.div(test_samples[i], preds[i]))

def main():

    # Please change the inputs here
    inputDim = 4

    # Additional inputs may not be required to change.
    learningRate = 0.0005
    batchSize = 64
    numberOfSteps = 10000

    # Additional Initializer
    device = torch.device('cpu')
    model =  NetworkModel(inputDim)
    trainer = TrainModel(model, device, learningRate, inputDim, batchSize, numberOfSteps)
    trainer.train()
    trainer.test(50)

if __name__ == '__main__':
    main()

[Parameter containing:
tensor([[ 0.3468, -0.7553, -1.1756,  1.3883],
        [ 0.3677,  1.1636, -1.4343, -0.6734],
        [-1.4603,  1.0083,  0.0106,  0.9223],
        [-1.2697, -1.0290, -0.7487, -0.8767]], requires_grad=True), Parameter containing:
tensor([[ 0.3468,  0.3677, -1.4603, -1.2697],
        [-0.7553,  1.1636,  1.0083, -1.0290],
        [-1.1756, -1.4343,  0.0106, -0.7487],
        [ 1.3883, -0.6734,  0.9223, -0.8767]], requires_grad=True)]
H*Ht = 
tensor([[ 4.0000e+00,  4.7684e-07,  2.3842e-07,  5.9605e-08],
        [ 4.7684e-07,  4.0000e+00, -5.9605e-08,  1.1921e-07],
        [ 2.3842e-07, -5.9605e-08,  4.0000e+00, -3.5763e-07],
        [ 5.9605e-08,  1.1921e-07, -3.5763e-07,  4.0000e+00]],
       grad_fn=<MmBackward0>)
Results: 
tensor([0.2500, 0.2500, 0.2500, 0.2500], grad_fn=<DivBackward0>)
tensor([0.2500, 0.2500, 0.2500, 0.2500], grad_fn=<DivBackward0>)
tensor([0.2500, 0.2500, 0.2500, 0.2500], grad_fn=<DivBackward0>)
tensor([0.2500, 0.2500, 0.2500, 0.2500], grad_fn=<D

In [3]:
from booleantools import *

x = getX(5)
print(x)

[BooleanFunction([[0]], 1), BooleanFunction([[1]], 2), BooleanFunction([[2]], 3), BooleanFunction([[3]], 4), BooleanFunction([[4]], 5)]
