In [23]:
f = open("had64.txt")

H64 = []
for i in range(64):
    H64.append([1.0 if i=='+' else -1.0 for i in list(f.readline())[:-1]])
    
print(H64)

# print([[H64[i][j]-H64[j][i] for i in range(64)] for j in range(64)])

[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0], [1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0

In [27]:

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from collections import OrderedDict

class NetworkModel(nn.Module):

    def __init__(self, inputDim):

        # Initialize the network layers.

        super(NetworkModel, self).__init__()

        self.lin1 = nn.Linear(inputDim, inputDim, bias=False)

    def forward(self, x):

        # A forward function
        # Linear function without activation

        x = self.lin1(x)
        
#         F-> WalshSpec
#         WalshSpec = F * W_t

        return x

class TrainModel():

    def __init__(self, model, device, learningRate, inputDim, batchSize, numberOfSteps, epochs):

        self.device = device
        self.net = model.to(self.device)
        self.optimizer = optim.Adam(self.net.parameters(), lr=learningRate)
        self.inputDim = inputDim
        self.batchSize = batchSize
        self.numberOfSteps = numberOfSteps
        self.epochs = epochs
        self.H = {}
        self.H[4] = torch.tensor([[1.0, 1.0, 1.0, 1.0], [1.0, -1.0, 1.0, -1.0], [1.0, 1.0, -1.0, -1.0], [1.0, -1.0, -1.0, 1.0]])
        self.H[8] = torch.tensor([[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                            [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0],
                            [1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0],
                            [1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0],
                            [1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0],
                            [1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0],
                            [1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0],
                            [1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0]])
        self.H[64] = H64
        if(self.inputDim<20):
#             For generating data of insuficcient LI inputs:
#             while(True):
#                 self.perm = torch.randperm(pow(2, self.inputDim))
# #                 print("Permutation of input numbers i.e. truth tables: \n", self.perm)
#                 self.data = [[0.0]*(self.inputDim-len(bin(num)[2:]))+[float(i) for i in bin(num)[2:]] for num in self.perm]
#                 if(np.linalg.matrix_rank(self.data[:self.numberOfSteps])>=self.inputDim):
#                     print("Rank not small enough, generating data again")
#                 else:
#                     break
            
            self.perm = torch.randperm(pow(2, self.inputDim))
            print("Permutation of input numbers i.e. truth tables: \n", self.perm)
            self.data = [[0.0]*(self.inputDim-len(bin(num)[2:]))+[float(i) for i in bin(num)[2:]] for num in self.perm]
            print("Rank is ", np.linalg.matrix_rank(self.data[:self.numberOfSteps]))
            print("Binary version of permutation: \n", self.data)
            
        else:
            
            print(0)
            
    
    def train(self, ):
        
        for ep in range(self.epochs):
            
            for step in range(self.numberOfSteps):

                self.optimizer.zero_grad()
                input = torch.tensor(self.data[step])
                output = self.net(input)
                loss = F.mse_loss(torch.matmul(input, self.H[self.inputDim]), output)
                loss.backward()
                self.optimizer.step()

            if ((ep+1)%100==0):
                weight_dict = OrderedDict(self.net.named_parameters())
                weightFunction = weight_dict['lin1.weight'].T
                print("ep= ", ep, "\n", weightFunction, 6)
        
        weight_dict = OrderedDict(self.net.named_parameters())
        weightFunction = weight_dict['lin1.weight'].T
        print("Final rounded weight function: \n", torch.round(weightFunction))



    def test(self,n):

#         test_samples = torch.tensor([[float(el) for el in row] for row in torch.randint(0, 2, (n, self.inputDim)).to(self.device)])
        test_samples = torch.tensor(self.data[self.numberOfSteps:self.numberOfSteps+n])    
        preds = self.net(test_samples)
        outputs = torch.matmul(test_samples, self.H[self.inputDim])
        print("Test:")
        for i in range(len(preds)):
            print(outputs[i], "\n", torch.round(preds[i]), "\n\n")


def main():

    # Please change the inputs here
    inputDim = 8

    # Additional inputs may not be required to change.
    learningRate = 0.005
    batchSize = 1
    numberOfSteps = 8
    epochs = 2000

    # Additional Initializer
    device = torch.device('cpu')
    model =  NetworkModel(inputDim)
    trainer = TrainModel(model, device, learningRate, inputDim, batchSize, numberOfSteps, epochs)
    trainer.train()
    trainer.test(10)

if __name__ == '__main__':
    main()

Permutation of input numbers i.e. truth tables: 
 tensor([175, 185, 179,  15, 143,  75, 229, 207, 227, 113, 154,  66,  20, 213,
        180,  84, 114, 169, 132, 151,  46,  85, 152, 149, 250, 189, 150, 147,
        247,  27, 217,  60,  54, 253,  19,  99, 237, 112, 203, 246, 239, 181,
        199,   2, 214, 108, 224,  88, 100,  74,  51,  69, 252, 188, 200,  76,
         33, 202, 233, 170, 235,  39,  43, 212,  81, 172, 140,  53, 194,  52,
         12, 238, 109, 125, 166, 232,  63, 110, 138, 103, 167,  87, 111, 131,
         83, 216,  91, 223, 141, 178,  16, 206, 168,  22, 197,   9,   0, 174,
         57, 243,  94,  44,  42, 244,  59, 124,  30, 191, 231, 164,  61,  14,
         21, 218, 142,   3,   4, 145, 225, 102,  49, 118, 190, 193, 209,  36,
        129, 245, 123,  28, 236, 130, 162, 155,  62,  17, 176, 230, 177, 226,
        128,   7,  86, 139,  73, 201,  89,  29, 228,   6, 104,  72, 106, 117,
        163, 156,  23,  34,  65, 186,  48, 160,  11,  96, 234, 242, 220,  58,
         25,  

ep=  99 
 tensor([[ 1.1771,  0.4317,  0.2672,  0.5434,  0.3469,  1.0017,  0.4120,  0.4333],
        [ 0.7274, -1.0886,  0.7442, -0.8499,  0.5211, -0.5253,  1.2004, -0.9996],
        [ 0.9458,  0.2925, -0.7036,  0.0436,  0.9286,  1.1677, -0.6119, -0.4789],
        [ 0.7012, -0.0601, -1.1270,  0.5856,  1.1878, -0.7329, -0.1760,  0.3402],
        [ 0.9251,  0.3738,  0.3445,  0.8533, -1.1675, -0.6212, -0.3157, -0.4664],
        [ 0.8507, -0.2473,  0.9041, -0.8743, -0.5874,  0.8404, -0.2157,  0.5961],
        [ 1.0661,  0.5662, -0.5164, -0.2590, -1.0208, -0.6494,  0.7053,  0.3094],
        [ 1.1640, -0.0729, -0.2403,  0.3253, -0.4266,  0.2249,  0.1824, -0.2666]],
       grad_fn=<PermuteBackward0>) 6
ep=  199 
 tensor([[ 1.1426,  0.6635,  0.6122,  0.7205,  0.6133,  1.0139,  0.5865,  0.7947],
        [ 0.8782, -1.1264,  0.8395, -0.8371,  0.8957, -0.7413,  1.3447, -1.2047],
        [ 0.9563,  0.5450, -0.8749, -0.3047,  0.9373,  1.2414, -0.7287, -0.7912],
        [ 0.7371, -0.5262, -1.1759,  0.

ep=  1299 
 tensor([[ 0.9999,  1.0018,  1.0000,  1.0000,  1.0003,  1.0001,  0.9999,  1.0000],
        [ 1.0001, -1.0092,  1.0000, -1.0000,  0.9997, -1.0001,  1.0001, -0.9999],
        [ 1.0001,  1.0022, -1.0000, -1.0000,  0.9997,  0.9999, -0.9999, -1.0000],
        [ 1.0002, -0.9938, -1.0001,  0.9999,  0.9991, -1.0002, -0.9998,  1.0001],
        [ 1.0001,  1.0070,  1.0000,  1.0000, -1.0002, -1.0001, -0.9999, -1.0000],
        [ 1.0002, -0.9979,  0.9999, -1.0000, -1.0005,  0.9998, -0.9999,  1.0001],
        [ 1.0001,  1.0076, -1.0000, -1.0000, -1.0002, -1.0001,  1.0001,  1.0000],
        [ 0.9997, -0.9955, -0.9999,  1.0001, -0.9992,  1.0002,  0.9998, -1.0001]],
       grad_fn=<PermuteBackward0>) 6
ep=  1399 
 tensor([[ 1.0001,  1.0001,  1.0000,  0.9999,  1.0008,  0.9999,  1.0000,  1.0000],
        [ 0.9999, -1.0004,  1.0000, -0.9999,  0.9939, -0.9999,  1.0001, -1.0000],
        [ 0.9999,  1.0001, -1.0000, -0.9999,  1.0033,  1.0000, -1.0000, -1.0000],
        [ 0.9998, -0.9998, -0.9999, 

In [1]:
import numpy as np

print(np.linalg.matrix_rank([[0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0], [0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0], [1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0], [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]))

8
